// 処理系のテスト５３
// 異常ケース４２: 宣言されていない手続きの呼び出し

void main()
{
  move(10);	// move() は宣言されていないのでエラー
}

