// 処理系のテスト２８
// 異常ケース１７: 引数なしで宣言された手続きを引数ありで呼び出し

int move();

int move()
{
  return 3;
}

void main()
{
  int log = 7;
  // move() は引数なしで宣言されているのに
  // １引数を与えて呼び出しているのでエラー
  move(log);
}
